auto: true
server: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title
paginate: 10
baseurl: http://idodev.co.uk
prose:
  metadata:
    "_posts": |
      layout: post
      published: false
      date: YYYY-MM-DD
      author: Toby Foord
      title: Title of your article
      slug: title-of-your-article
