auto: true
server: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title
paginate: 10
prose: 
    rooturl: "_posts"
    metadata:
        "_posts": |
	        layout: "post"
	        date: "YYYY-MM-DD"
			slug: "title-of-your-post"
			title: "Title of your post"
			author: "Toby Foord"