auto: true
server: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title
paginate: 5
baseurl: http://idodev.co.uk
prose:
  siteurl: "http://idodev.co.uk"

prose:
  siteurl: 'http://idodev.co.uk'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "metatitle"
        field:
          element: "text"
          label: "Meta Title"
          value: ""
      - name: "metadesc"
        field:
          element: "textarea"
          label: "Meta Description"
          value: ""
      - name: "img"
        field:
          element: "text"
          label: "Headline Image"
          value: ""
