auto: true
server: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title
paginate: 10
prose:
  metadata:
    "_posts": |
      author: "Toby Foord"
      title: "Title of your article"
      slug: "title-of-your-article"